replicaCount: 1

image:
  repository: 711387125079.dkr.ecr.ap-south-1.amazonaws.com/idp-demo-service
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer # ClusterIP
  port: 80
  targetPort: 3000

resources: {}
