apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shryshs/idp-gitops-demo.git'
    targetRevision: HEAD
    path: apps/demo-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
